services:
  db:
    image: mariadb:10.11
    container_name: aiscanner_db
    restart: always
    network_mode: host
    environment:
      - TZ=America/Costa_Rica
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --port=${MYSQL_PORT}
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: aiscanner_redis
    restart: always
    network_mode: host
    environment:
      - TZ=America/Costa_Rica
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
    container_name: aiscanner_backend
    privileged: true
    restart: always
    network_mode: host
    environment:
      - TZ=America/Costa_Rica
      - DATABASE_URL=mysql+aiomysql://${MYSQL_USER}:${MYSQL_PASSWORD}@localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
      - REDIS_URL=redis://localhost:6379/0
      - BACKEND_PORT=${BACKEND_PORT}
      - NESSUS_API_URL=${NESSUS_API_URL}
      - OPENVAS_API_URL=${OPENVAS_API_URL}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: aiscanner_frontend
    restart: always
    network_mode: host
    environment:
      - TZ=America/Costa_Rica
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_API_URL=http://localhost:${BACKEND_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mariadb_data:
  redis_data:
